dependencies:
  - python=3
  - pip:
    - scipy
    - numpy
    - turtle
    - pandas
    - matplotlib
    - spacy
    - ipykernel
    - scikit-learn
    - thinc
    - tqdm
    - sklearn
    - Pillow
    - xgboost
    - sympy
    - requests
    - lightgbm
    - catboost
    - Seaborn
    - ggplot
    - Bokeh
    - Plotly
    - pygal
    - geoplotlib
    - missingno
    - StatsModels
    - scrapy
    - BeautifulSoup4
    - pymongo
